### PR TITLE
Allow setting insert mode on new scratch buffer.

### PR DESCRIPTION
**Pull request by kevintraver**
This allows setting insert mode when entering the new scratch buffer.

### CODE REVIEW

**Comment by brettanomyces** [comment]
Hi @kevintraver, thanks for the PR!

You can enter insertmode after opening the scratch buffer by redefining the mapping to open the scratch buffer in your `$MYVIMRC`.

```
let g:editcommand_no_mappings = 1
tmap <c-x><c-e> <Plug>EditCommand A
```

I'd prefer to not make changes to the code unless absolutely necessary but if there's a use case that this doesn't solve I'd consider adding the extra option.

**Comment by kevintraver** [comment]
Ok, thanks for the feedback.

Just curious, what would you do if you had something like this set:

`autocmd BufWinEnter,WinEnter term://* startinsert`

and then in the `editcommand` scratch buffer you wanted to override and stop insert mode?

**Comment by brettanomyces** [comment]
I'm away from a computer at the moment so I can't test but I'd try putting
<esc> or <c-\><c-h> in place of the A in the mapping

**Comment by kevintraver** [comment]
On a sort of related note...

What if you wanted to have the `enter` key close the scratch buffer? Is there a way to detect the `editcommand` buffer type and set a local key map?

**Comment by brettanomyces** [comment]
The scratch buffer has buftype 'nofile' so you can set up an autocmd for buffers 'nofile' buftype which creates a mapping

```
:autocmd BufReadPost nofile nnoremap <buffer> <CR> :bdelete<CR>
```

**Pull request closed without merging**
